version: '3'

services:
  otel-collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.129.1
    command: ["--config=/etc/otel-collector-config.yaml"]
    user: 0:0
    volumes:
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP receiver
      - "4318:4318" # OTLP receiver
      - "8889:8889" # Prometheus metrics
  jaeger:
    image: jaegertracing/all-in-one:latest
    command:
      - "--memory.max-traces=25000"
      - "--query.base-path=/jaeger/ui"
    ports:
      - "16686:16686" # Jaeger UI
      - "14317:14317" # Jaeger OTLP receiver (port différent pour éviter conflit)

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --web.enable-otlp-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - "9090:9090"