# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

global:
  # Align Prometheus scrape interval with the OTel SDKs' export interval for consistency (see OTEL_METRIC_EXPORT_INTERVAL)
  scrape_interval: 60s

otlp:
  keep_identifying_resource_attributes: true
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - cloud.availability_zone
    - cloud.region
    - deployment.environment.name

    # When deploying on VMs, resource attributes used to identify
    # the host in dashboards and alerts.
    - host.name
storage:
  tsdb:
    out_of_order_time_window: 30m


scrape_configs:
  - job_name: 'otel-collector2'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '.*'
        action: keep
