# Logging configuration
logging:
  # Global log level
  level:
    root: INFO
    com.exemple.demo: DEBUG
    org.springframework: WARN
    org.hibernate: WARN
  
  # Log pattern configuration
  pattern:
    # Pattern for console with colors
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    # Pattern for files
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : %m%n%wEx"
  
  # Log files configuration
  file:
    name: logs/demo-app.log
    max-size: 10MB
    max-history: 30
    total-size-cap: 1GB

# Configuration de l'application
spring:
  application:
    name: observability-logs-demo
  
  # Active profile configuration
  profiles:
    active: development

# Custom configuration for demonstration
demo:
  logging:
    enabled: true
    simulation:
      error-rate: 0.3
      delay-ms: 100

---
# Development profile
spring:
  config:
    activate:
      on-profile: development
      
logging:
  level:
    com.exemple.demo: TRACE
    
---
# Production profile
spring:
  config:
    activate:
      on-profile: production
      
logging:
  level:
    root: WARN
    com.exemple.demo: INFO
  file:
    name: /var/log/demo-app/application.log
